/**
 * Created by andrew.fenner on 07/10/2016.
 */
({
    doInit:function(component,event,helper){
        helper.doInit(component,event,helper);
    },
    changeJournalType:function(component,event,helper){
        helper.changeJournalType(component,event,helper);
    },
    changeItemTags:function(component,event,helper){
        helper.changeItemTags(component,event,helper);
    },
    togglePayButton:function(component,event,helper){
        helper.togglePayButton(component,event,helper);
    },
    tagsChanged:function(component,event,helper){
        helper.tagsChanged(component,event,helper);
    }
})